term.clear()
shell.run("rm startup.lua")
shell.run("rm Login.lua")
shell.run("rm Desktop.lua")
shell.run("rm FileManager.lua")
shell.run("rm MinuxNews.lua")
shell.run("rm update.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/main/startup.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/main/Login.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/main/Desktop.lua")
shell.run("wget https://raw.githubusercontent.com/kazu55/MinuxGUI/main/MinuxNews.lua")
shell.run("wget https://pastebin.com/raw/pnzdr8FB")
os.reboot()
